include:
  - project: "GNOME/citemplates"
    file: "templates/default-rules.yml"
  - component: gitlab.gnome.org/GNOME/citemplates/gnomeos-basic-ci@master
  - component: gitlab.gnome.org/GNOME/citemplates/release-service@master
    inputs:
      dist-job-name: "build-gnomeos"
      tarball-artifact-path: "_builddir/meson-dist/$CI_PROJECT_NAME-$CI_COMMIT_TAG.tar.xz"

stages:
    - build
    - docs
    - deploy

variables:
    FEDORA_IMAGE: "registry.fedoraproject.org/fedora:41"

reference:
    image: $FEDORA_IMAGE
    stage: docs
    needs: []
    variables:
        MESON_FLAGS: "-Denchant=enabled -Dvapi=true"
    script:
        - sudo dnf install -y gtk4-devel
                ccache
                desktop-file-utils
                editorconfig-devel
                enchant2-devel
                expat-devel
                gcc
                gcc-c++
                gettext
                gi-docgen
                gi-docgen-fonts
                git
                glib2-devel
                gobject-introspection-devel
                gtk4-devel
                gtksourceview5-devel
                itstool
                libadwaita-devel
                libicu-devel
                libjpeg-turbo-devel
                libpng-devel
                libxkbcommon-devel
                libXrandr-devel
                libXi-devel
                libXcursor-devel
                libXdamage-devel
                libXinerama-devel
                libdrm-devel
                libglvnd-devel
                glslc
                mesa-vulkan-drivers
                meson
                ninja-build
                redhat-rpm-config
                shared-mime-info
                vala
                xorg-x11-server-Xvfb
                vulkan-devel
                vulkan-headers
                vulkan-loader-devel
        - mkdir -p pfx/
        - meson ${MESON_FLAGS} --prefix=${PWD}/pfx _build
                -Dwerror=false
                -Dglib:werror=false
                -Dgtk:broadway-backend=false
                -Dgtk:build-examples=false
                -Dgtk:build-tests=false
                -Dgtk:build-testsuite=false
                -Dgtk:build-demos=false
                -Dgtk:media-gstreamer=disabled
                -Dgtk:werror=false
                -Dgtksourceview:documentation=false
                -Dgtksourceview:introspection=disabled
                -Dgtksourceview:vapi=false
                -Dgtksourceview:werror=false
                -Dicu:werror=false
                -Dpango:gtk_doc=false
                -Dpango:introspection=disabled
                -Dpango:werror=false
                -Dwayland-protocols:tests=false
                -Dwayland:documentation=false
                -Dwayland:dtd_validation=false
                -Dwayland:tests=false
        - ninja -C _build install
        - mkdir -p _reference/
        - mv pfx/share/doc/libspelling-1/ _reference/
    artifacts:
        paths:
            - _reference

pages:
    stage: deploy
    needs: ['reference']
    script:
        - mv _reference public/
    artifacts:
        paths:
            - public
    only:
        - main
