include:
  - project: "GNOME/citemplates"
    file: "templates/default-rules.yml"
  - component: gitlab.gnome.org/alatiera/citemplates/gnomeos-basic-ci@alatiera/gnomeos-gen-docs
    inputs:
      docs-path: "share/doc/libspelling-1"
  - component: gitlab.gnome.org/GNOME/citemplates/release-service@master
    inputs:
      dist-job-name: "build-gnomeos"
      tarball-artifact-path: "_builddir/meson-dist/$CI_PROJECT_NAME-$CI_COMMIT_TAG.tar.xz"

stages:
    - build
    - deploy

pages:
    stage: "deploy"
    needs: ["build-gnomeos"]
    script:
        - untar ${CI_PROJECT_NAME}-docs.tar public/
    artifacts:
        paths:
            - public
    only:
        - main
